version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
            - ELASTIC_PASSWORD=changeme
            - xpack.security.enabled=true
        ports:
            - 9200:9200
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - docker_airlux_network

    kibana:
        image: docker.elastic.co/kibana/kibana:8.7.0
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=changeme
        ports:
            - 5601:5601
        networks:
            - docker_airlux_network
    
    logstash:
        image: docker.elastic.co/logstash/logstash:8.7.0
        container_name: logstash
        volumes:
            - ./logstash/config:/usr/share/logstash/pipeline/
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=changeme
        ports:
            - 5044:5044
            - 9600:9600
        networks:
            - docker_airlux_network

    filebeat:
        image: docker.elastic.co/beats/filebeat:8.7.0
        user: root
        volumes:
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            - /var/lib/docker:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - docker_airlux_network

volumes:
    elasticsearch_data:

networks:
    docker_airlux_network:
      external: true