# Création des Container
services:
    # Création du container Redis-Stack
    redis-stack:
      image: redis/redis-stack:latest
      container_name: redis-stack
      restart: unless-stopped
      hostname: redis
      volumes:
        - ./redis-stack:/data
      ports:
        - 6379:6379
        - 8001:8001
    # Création du conteneur API locale
    api_local:
      container_name: api_local
      depends_on:
        - redis-stack
      image: nanodeus/docker_api_local
      restart: unless-stopped
      ports:
        # - 80:8080
        - 6869:8080
      stdin_open: true
      tty: true
