version: '3.8'

#Création des Container
services:
    #Création du container Redis
    redis:
        image: redis
        container_name: redis
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - ./local_server:/data
        build: local_server
        ports:
          - 6379
          
    #Création du container MySQL      
    mysql:
        image: mysql
        container_name: db
        restart: unless-stopped
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_USER=users
          - MYSQL_DATABASE=db
        volumes:
          - ./cloud_server:/data
        build: cloud_server

    #création de l'API distante
    app:
      depends_on:
        - mysql
      build: ./distant_api/
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
      environment:
        - DB_HOST=mysqldb
        - DB_USER=$MYSQLDB_USER
        - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - DB_NAME=$MYSQLDB_DATABASE
        - DB_PORT=$MYSQLDB_DOCKER_PORT
      stdin_open: true
      tty: true

    #Création du container Debian
    pulseur:
        image: pulseur
        container_name: pulseur
        stdin_open: true
        tty: true
        volumes:
          - ./pulse_bdd:/data
        build: pulse_bdd
        ports:
          - 7080:83
