version: '3.8'

#Création des Container
services:
    #Création du container Redis
    redis:
        container_name: redis
        restart: unless-stopped
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - ./local_server:/data
        build: local_server
        ports:
          - 6379
        depends_on: 
          - mosquitto

     #Création de l'insertion Redis
    local_insertion:
        container_name: redis_insertion
        restart: unless-stopped
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - ./local_insertion:/data
        build: local_insertion
        ports:
          - 6380
        depends_on: 
          - redis
          
    #Création du container MySQL      
    mysql:
        image: mysql
        container_name: db
        restart: unless-stopped
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_USER=user
          - MYSQL_DATABASE=db
        volumes:
          - ./cloud_server:/data
        build: cloud_server
        ports:        
          - 3306:3306
        expose :
          - 3306

    #Création du container Debian Pulseur
    pulseur:
        container_name: pulseur
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
          - ./pulse_bdd:/data
        build: pulse_bdd
        ports:
          - 7080:83
          
    #Création du conteneur API distante
    appmysql:
      depends_on:
        - mysql
      build: ./distant_api
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      environment:
        - DB_HOST=mysql
        - DB_USER=$MYSQLDB_USER
        - DB_PASSWORD=$MYSQLDB_PASSWORD
        - DB_NAME=$MYSQLDB_DATABASE
        - DB_PORT=$MYSQLDB_DOCKER_PORT
      stdin_open: true
      tty: true
      
    #Création du conteneur API distante
    appredis:
      depends_on:
        - redis
      build: ./local_api
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_DISTANT_PORT:$NODE_DOCKER_PORT
      environment:
        - DB_HOST=redis
        - DB_PORT=6379
      stdin_open: true
      tty: true

