version: '3.8'

services:
    redis:
        image: redis
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - redis:/data
        ports:
          - 6379
          
    mysql:
        image: mysql
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - mysql:/data
        ports:        
          - 3306:80

    pulseur:
        image: pulseur
        stdin_open: true
        tty: true
        volumes:
          - pulseur:/data
        ports:
          - 7080:83
        
volumes:
    mysql:
    redis:
    pulseur: