version: '3.8'

#Création des Container
services:
    #Création du container Redis
    redis:
        image: redis
        container_name: redis
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - ./local_server:/data
        build: local_server
        ports:
          - 6379
          
    #Création du container MySQL      
    mysql:
        image: mysql
        container_name: db
        restart: unless-stopped
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_USER=user
          - MYSQL_DATABASE=db
        volumes:
          - ./cloud_server:/data
        build: cloud_server
        ports:        
          - 3306:3306
        expose :
          - 3306

    #Création du container Debian
    pulseur:
        image: pulseur
        container_name: pulseur
        stdin_open: true
        tty: true
        volumes:
          - ./pulse_bdd:/data
        build: pulse_bdd
        ports:
          - 7080:83
    
    #Création du container Debian
    reader:
        image: reader
        container_name: reader
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
          - ./reader:/data
        build: reader
        ports:
          - 8000
        command: sh -c "sleep 10s"
        depends_on :
          - mysql
        
