version: '3.8'

# Création des Container
services:

    # Création du container Redis-Stack
    redis-stack:
      image: redis/redis-stack:latest
      container_name: redis-stack
      restart: unless-stopped
      hostname: redis
      volumes:
        - ./redis_stack/data:/data
      ports:
        - 6379:6379
        - 8001:8001
    
    # Création du conteneur API locale
    api_local:
      container_name: api_local
      depends_on:
        - redis-stack
      build: ./local_api
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_DISTANT_PORT:$NODE_DOCKER_PORT
      stdin_open: true
      tty: true
          
    # Création du container MySQL      
    mysql:
      container_name: mysql
      image: mysql
      restart: unless-stopped
      env_file: ./.env
      environment:
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      volumes:  
        - ./mysql/data:/var/lib/mysql 

    # Création du conteneur API distante
    appmysql:
      container_name: appmysql
      depends_on:
        - mysql
      build: ./distant_api
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      environment:
        - DB_HOST=mysql
        - DB_USER=$MYSQLDB_USER
        - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - DB_NAME=$MYSQLDB_DATABASE
        - DB_PORT=$MYSQLDB_DOCKER_PORT
      stdin_open: true
      tty: true
    
    # Création d'un container grafana
    # grafana:
    #   image: grafana/grafana:7.5.4
    #   restart: unless-stopped
    #   env_file: ./.env
    #   ports:
    #     - 3000:3000
    #   depends_on:
    #     - mysql
    #   environment:
    #     GF_SECURITY_ADMIN_USER: $GF_USER
    #     GF_SECURITY_ADMIN_PASSWORD: $GF_PASSWORD
    #     GF_DATABASE_TYPE: $GF_DATABASE_TYPE
    #     GF_DATABASE_HOST: $GF_DATABASE_HOST
    #     GF_DATABASE_NAME: $MYSQLDB_DATABASE
    #     GF_DATABASE_USER: $MYSQLDB_USER
    #     GF_DATABASE_PASSWORD: $MYSQLDB_ROOT_PASSWORD

    # Création du container Mosquitto       
    mosquitto:
      image: eclipse-mosquitto
      restart: unless-stopped
      container_name: mosquitto
      hostname: mqtt
      volumes:
        - ./mosquitto/config/:/mosquitto/config/:rw
        - ./mosquitto/data:/mosquitto/data/
        - ./mosquitto/log:/mosquitto/log/
      ports:
        - 1883:1883 # MQTT Port
        - 9001:9001 # WS Port
