version: '3.8'

#Création des Container
services:
    #Création du container Redis
    redis:
        image: redis
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - ./local_server:/data
        build: local_server
        ports:
          - 6379
          
    #Création du container MySQL      
    mysql:
        image: mysql
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_DATABASE=db
        volumes:
          - ./cloud_server:/data
        build: cloud_server
        ports:        
          - 3306:80

    #Création du container Debian
    pulseur:
        image: pulseur
        stdin_open: true
        tty: true
        volumes:
          - ./pulse_bdd:/data
        build: pulse_bdd
        ports:
          - 7080:83
    
    #Création du container Debian
    reader:
        image: reader
        stdin_open: true
        tty: true
        volumes:
          - ./reader:/data
        build: reader
        ports:
          - 8000
        
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        network_mode: host
        volumes:
          - ./conf:/mosquitto/conf
          - ./data:/mosquitto/data
          - ./log:/mosquitto/log
        build: mosquitto
        ports:
          - "1883:1883" # MQTT Port
          - "9001:9001" # WS Port
