version: '3.8'

#Création des Container
services:
    #Création du container Redis
    redis:
        container_name: redis
        #network_mode: host
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
          - ./local_server/data:/data
        build: local_server
        ports:
          - 6379
          
    #Création du container MySQL      
    mysql:
        image: mysql
        container_name: db
        restart: unless-stopped
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_USER=user
          - MYSQL_DATABASE=db
        volumes:
          - ./cloud_server/data:/data
        ports:        
          - 3306:3306

    #Création du container Debian Pulseur
    pulseur:
        container_name: pulseur
        restart: unless-stopped
        stdin_open: true
        #network_mode: host
        tty: true
        volumes:
          - ./pulse_bdd:/data
        build: pulse_bdd
        ports:
          - 7080:83
        depends_on: 
          - mosquitto

    #Création du container Mosquitto       
    mosquitto:
        image: eclipse-mosquitto
        restart: unless-stopped
        container_name: mosquitto
        #network_mode: host
        volumes:
          - ./mosquitto/config/:/mosquitto/config/:rw
          - ./mosquitto/data:/mosquitto/data/
          - ./mosquitto/log:/mosquitto/log/
        ports:
          - 1883:1883 # MQTT Port
          - 9001:9001 # WS Port