global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

remote_write:
  - url: "https://eu1.app.sysdig.com/prometheus/remote/write"
    basic_auth:
      username: "seillenicolas"
      password: "airlux"
