name: Flutter-CI
run-name: Flutter-CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      run: |
        cd mobileapp
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests on emulator
        run: |
          flutter emulators --launch emulator
          flutter test
