name: Flutter-CI
run-name: Flutter-CI
on:
  push:
    branches:
      - lacazej/workflows
      - main
  pull_request:
    branches:
      - lacazej/workflows
      - main
jobs:
  Flutter-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobileapp/

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Get dependencies
        run: flutter pub get

      #- name: Run tests on emulator
       # run: |
        #  flutter emulators --launch emulator
        #  flutter test
  API-Locale-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker/local_api/

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
          cache-dependency-path: './docker/local_api/package-lock.json'

      - name: Get dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:fix
      
      - name: Run ESLint if JavaScript files changed
        if: ${{ github.event_name == 'push' && github.event.head_commit.modified == 'javascript' }}
        run: npm run lint