name: Flutter-CI
run-name: Flutter-CI
on:
  push:
    branches:
      - lacazej/workflow
      - develop
      - main
  pull_request:
    branches:
      - lacazej/workflow
      - develop
      - main
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
        steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: 'stable'
      - run: flutter --version
      - name: Install dependencies
        run: dart pub get
        with:
          working-directory: ./mobileapp/
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze --fatal-infos

  API-Locale:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker/local_api/

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
          cache-dependency-path: './docker/local_api/package-lock.json'

      - name: Get dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:fix

      - name: Start Docker Compose for unit tests & RUN
        run: |
          docker-compose up -d
          sleep 5
          docker ps
      
      - name: Run unit tests
        run: npm run test:unit
  


  deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker/local_api/
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up SSH connection
        run: echo "Coucou"