name: Flutter-CI
run-name: Flutter-CI
on:
  push:
    branches:
      - lacazej/workflow
      - develop
      - main
  pull_request:
    branches:
      - lacazej/workflow
      - develop
      - main
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: flutter pub get
        with:
          working-directory: ./mobileapp
      - name: Run linter
        run: flutter analyze

  API-Locale:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker/local_api/

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
          cache-dependency-path: './docker/local_api/package-lock.json'

      - name: Get dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:fix

      - name: Start Docker Compose for unit tests & RUN
        run: |
          docker-compose up -d
          sleep 5
          docker ps
      
      - name: Run unit tests
        run: npm run test:unit
  


  deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker/local_api/
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up SSH connection
        run: echo "Coucou"